import axios from "axios";
import constants from "constants/constants";

/**
 * Get the list of ships in the given region
 * @param {Object} regionName
 * @returns {Array}
 */

export const getVesselsListInARegion = async (regionName) => {
  const result = await axios.get(
    `${constants.BASE_URL}/getVesselsInArea/${regionName}`
  );

  if (result.data === null) return [];

  return result.data;
};

/**
 * Get the details of a particular vessel
 * @params {String} mmsi
 * @returns {Object}
 */

export const getDetailsOfAVessel = async (mmsi) => {
  const result = await axios.get(
    `${constants.BASE_URL}/getLastPosition/${mmsi}`
  );

  return result.data;
};

/**
 * Get the details of a particular vessel
 * @params {String} mmsi
 * @returns {Object}
 */

export const getMoreDatailsOfAVessel = async (mmsi) => {
  const result = await axios.get(
    `${constants.BASE_URL}/getMoreDetails/${mmsi}`
  );

  return result.data;
};

/**
 * Get the weather details of a region
 * @params {String} mmsi
 * @returns {Object}
 */

export const getWeatherDetails = async (lat, lon) => {
  const result = await axios.get(
    `http://api.worldweatheronline.com/premium/v1/marine.ashx?key=${constants.WEATHER_API_KEY}&format=json&q=${lat},${lon}`
  );

  return result.data;
  const data = {
    data: {
      request: [
        {
          type: "LatLon",
          query: "Lat 45.00 and Lon -2.00",
        },
      ],
      weather: [
        {
          date: "2021-01-23",
          astronomy: [
            {
              sunrise: "08:35 AM",
              sunset: "06:02 PM",
              moonrise: "01:37 PM",
              moonset: "03:53 AM",
              moon_phase: "Waxing Gibbous",
              moon_illumination: "69",
            },
          ],
          maxtempC: "12",
          maxtempF: "53",
          mintempC: "8",
          mintempF: "46",
          hourly: [
            {
              time: "0",
              tempC: "11",
              tempF: "52",
              windspeedMiles: "30",
              windspeedKmph: "48",
              winddirDegree: "270",
              winddir16Point: "W",
              weatherCode: "122",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Overcast",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "68",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1005",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "11",
              HeatIndexF: "52",
              DewPointC: "5",
              DewPointF: "42",
              WindChillC: "8",
              WindChillF: "46",
              WindGustMiles: "32",
              WindGustKmph: "51",
              FeelsLikeC: "8",
              FeelsLikeF: "46",
              sigHeight_m: "1.4",
              swellHeight_m: "3.6",
              swellHeight_ft: "11.8",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.2",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "300",
              tempC: "12",
              tempF: "53",
              windspeedMiles: "39",
              windspeedKmph: "63",
              winddirDegree: "254",
              winddir16Point: "WSW",
              weatherCode: "296",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain",
                },
              ],
              precipMM: "1.5",
              precipInches: "0.1",
              humidity: "71",
              visibility: "9",
              visibilityMiles: "5",
              pressure: "1002",
              pressureInches: "30",
              cloudcover: "94",
              HeatIndexC: "12",
              HeatIndexF: "53",
              DewPointC: "7",
              DewPointF: "44",
              WindChillC: "8",
              WindChillF: "46",
              WindGustMiles: "46",
              WindGustKmph: "74",
              FeelsLikeC: "8",
              FeelsLikeF: "46",
              sigHeight_m: "2.0",
              swellHeight_m: "3.8",
              swellHeight_ft: "12.5",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.3",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "600",
              tempC: "12",
              tempF: "53",
              windspeedMiles: "43",
              windspeedKmph: "70",
              winddirDegree: "271",
              winddir16Point: "W",
              weatherCode: "299",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0026_heavy_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Moderate rain at times",
                },
              ],
              precipMM: "3.5",
              precipInches: "0.1",
              humidity: "65",
              visibility: "8",
              visibilityMiles: "4",
              pressure: "1000",
              pressureInches: "30",
              cloudcover: "78",
              HeatIndexC: "12",
              HeatIndexF: "53",
              DewPointC: "6",
              DewPointF: "42",
              WindChillC: "8",
              WindChillF: "46",
              WindGustMiles: "52",
              WindGustKmph: "83",
              FeelsLikeC: "8",
              FeelsLikeF: "46",
              sigHeight_m: "2.3",
              swellHeight_m: "4.8",
              swellHeight_ft: "15.7",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.8",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "900",
              tempC: "11",
              tempF: "52",
              windspeedMiles: "41",
              windspeedKmph: "67",
              winddirDegree: "274",
              winddir16Point: "W",
              weatherCode: "116",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Partly cloudy",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "63",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1001",
              pressureInches: "30",
              cloudcover: "33",
              HeatIndexC: "11",
              HeatIndexF: "52",
              DewPointC: "5",
              DewPointF: "40",
              WindChillC: "7",
              WindChillF: "44",
              WindGustMiles: "63",
              WindGustKmph: "101",
              FeelsLikeC: "7",
              FeelsLikeF: "44",
              sigHeight_m: "2.2",
              swellHeight_m: "5.3",
              swellHeight_ft: "17.4",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.1",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1200",
              tempC: "10",
              tempF: "50",
              windspeedMiles: "38",
              windspeedKmph: "62",
              winddirDegree: "283",
              winddir16Point: "WNW",
              weatherCode: "119",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Cloudy",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "69",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1003",
              pressureInches: "30",
              cloudcover: "64",
              HeatIndexC: "10",
              HeatIndexF: "50",
              DewPointC: "5",
              DewPointF: "40",
              WindChillC: "5",
              WindChillF: "41",
              WindGustMiles: "45",
              WindGustKmph: "72",
              FeelsLikeC: "5",
              FeelsLikeF: "41",
              sigHeight_m: "2.0",
              swellHeight_m: "5.5",
              swellHeight_ft: "18.0",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.6",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1500",
              tempC: "9",
              tempF: "49",
              windspeedMiles: "23",
              windspeedKmph: "38",
              winddirDegree: "300",
              winddir16Point: "WNW",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "63",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1002",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "9",
              HeatIndexF: "49",
              DewPointC: "3",
              DewPointF: "37",
              WindChillC: "7",
              WindChillF: "44",
              WindGustMiles: "35",
              WindGustKmph: "56",
              FeelsLikeC: "7",
              FeelsLikeF: "44",
              sigHeight_m: "1.1",
              swellHeight_m: "5.0",
              swellHeight_ft: "16.4",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "13.1",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1800",
              tempC: "8",
              tempF: "46",
              windspeedMiles: "10",
              windspeedKmph: "16",
              winddirDegree: "325",
              winddir16Point: "NW",
              weatherCode: "302",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0018_cloudy_with_heavy_rain.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Moderate rain",
                },
              ],
              precipMM: "2.9",
              precipInches: "0.1",
              humidity: "86",
              visibility: "7",
              visibilityMiles: "4",
              pressure: "1001",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "8",
              HeatIndexF: "46",
              DewPointC: "6",
              DewPointF: "42",
              WindChillC: "4",
              WindChillF: "40",
              WindGustMiles: "19",
              WindGustKmph: "30",
              FeelsLikeC: "4",
              FeelsLikeF: "40",
              sigHeight_m: "0.3",
              swellHeight_m: "4.3",
              swellHeight_ft: "14.1",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "12.1",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "2100",
              tempC: "8",
              tempF: "46",
              windspeedMiles: "13",
              windspeedKmph: "21",
              winddirDegree: "348",
              winddir16Point: "NNW",
              weatherCode: "266",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light drizzle",
                },
              ],
              precipMM: "0.8",
              precipInches: "0.0",
              humidity: "81",
              visibility: "2",
              visibilityMiles: "1",
              pressure: "1002",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "8",
              HeatIndexF: "46",
              DewPointC: "5",
              DewPointF: "40",
              WindChillC: "5",
              WindChillF: "41",
              WindGustMiles: "15",
              WindGustKmph: "23",
              FeelsLikeC: "5",
              FeelsLikeF: "41",
              sigHeight_m: "0.5",
              swellHeight_m: "3.6",
              swellHeight_ft: "11.8",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "11.9",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
          ],
        },
        {
          date: "2021-01-24",
          astronomy: [
            {
              sunrise: "08:34 AM",
              sunset: "06:03 PM",
              moonrise: "02:09 PM",
              moonset: "04:56 AM",
              moon_phase: "Full Moon",
              moon_illumination: "76",
            },
          ],
          maxtempC: "11",
          maxtempF: "52",
          mintempC: "8",
          mintempF: "47",
          hourly: [
            {
              time: "0",
              tempC: "8",
              tempF: "47",
              windspeedMiles: "13",
              windspeedKmph: "22",
              winddirDegree: "14",
              winddir16Point: "NNE",
              weatherCode: "296",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain",
                },
              ],
              precipMM: "1.9",
              precipInches: "0.1",
              humidity: "83",
              visibility: "9",
              visibilityMiles: "5",
              pressure: "1004",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "8",
              HeatIndexF: "47",
              DewPointC: "6",
              DewPointF: "42",
              WindChillC: "4",
              WindChillF: "40",
              WindGustMiles: "24",
              WindGustKmph: "39",
              FeelsLikeC: "4",
              FeelsLikeF: "40",
              sigHeight_m: "0.5",
              swellHeight_m: "3.1",
              swellHeight_ft: "10.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "11.8",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "300",
              tempC: "8",
              tempF: "47",
              windspeedMiles: "15",
              windspeedKmph: "24",
              winddirDegree: "285",
              winddir16Point: "WNW",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "1.6",
              precipInches: "0.1",
              humidity: "76",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1006",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "8",
              HeatIndexF: "47",
              DewPointC: "4",
              DewPointF: "40",
              WindChillC: "5",
              WindChillF: "41",
              WindGustMiles: "18",
              WindGustKmph: "29",
              FeelsLikeC: "5",
              FeelsLikeF: "41",
              sigHeight_m: "0.6",
              swellHeight_m: "2.7",
              swellHeight_ft: "8.9",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "11.6",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "600",
              tempC: "9",
              tempF: "48",
              windspeedMiles: "26",
              windspeedKmph: "42",
              winddirDegree: "257",
              winddir16Point: "WSW",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "2.1",
              precipInches: "0.1",
              humidity: "74",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1007",
              pressureInches: "30",
              cloudcover: "56",
              HeatIndexC: "9",
              HeatIndexF: "48",
              DewPointC: "4",
              DewPointF: "40",
              WindChillC: "6",
              WindChillF: "43",
              WindGustMiles: "38",
              WindGustKmph: "60",
              FeelsLikeC: "6",
              FeelsLikeF: "43",
              sigHeight_m: "1.2",
              swellHeight_m: "2.6",
              swellHeight_ft: "8.5",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.5",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "900",
              tempC: "10",
              tempF: "50",
              windspeedMiles: "27",
              windspeedKmph: "43",
              winddirDegree: "277",
              winddir16Point: "W",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.4",
              precipInches: "0.0",
              humidity: "67",
              visibility: "9",
              visibilityMiles: "5",
              pressure: "1007",
              pressureInches: "30",
              cloudcover: "72",
              HeatIndexC: "10",
              HeatIndexF: "50",
              DewPointC: "4",
              DewPointF: "40",
              WindChillC: "7",
              WindChillF: "45",
              WindGustMiles: "36",
              WindGustKmph: "57",
              FeelsLikeC: "7",
              FeelsLikeF: "45",
              sigHeight_m: "1.2",
              swellHeight_m: "2.8",
              swellHeight_ft: "9.2",
              swellDir: "230",
              swellDir16Point: "SW",
              swellPeriod_secs: "23.6",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1200",
              tempC: "11",
              tempF: "51",
              windspeedMiles: "31",
              windspeedKmph: "50",
              winddirDegree: "259",
              winddir16Point: "WSW",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "0.5",
              precipInches: "0.0",
              humidity: "68",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1007",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "11",
              HeatIndexF: "51",
              DewPointC: "5",
              DewPointF: "41",
              WindChillC: "7",
              WindChillF: "45",
              WindGustMiles: "32",
              WindGustKmph: "51",
              FeelsLikeC: "7",
              FeelsLikeF: "45",
              sigHeight_m: "1.5",
              swellHeight_m: "2.7",
              swellHeight_ft: "8.9",
              swellDir: "230",
              swellDir16Point: "SW",
              swellPeriod_secs: "23.6",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1500",
              tempC: "11",
              tempF: "52",
              windspeedMiles: "34",
              windspeedKmph: "55",
              winddirDegree: "262",
              winddir16Point: "W",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "1.0",
              precipInches: "0.0",
              humidity: "72",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1005",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "11",
              HeatIndexF: "52",
              DewPointC: "6",
              DewPointF: "43",
              WindChillC: "7",
              WindChillF: "45",
              WindGustMiles: "42",
              WindGustKmph: "68",
              FeelsLikeC: "7",
              FeelsLikeF: "45",
              sigHeight_m: "1.7",
              swellHeight_m: "3.1",
              swellHeight_ft: "10.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.3",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1800",
              tempC: "11",
              tempF: "52",
              windspeedMiles: "37",
              windspeedKmph: "59",
              winddirDegree: "283",
              winddir16Point: "WNW",
              weatherCode: "356",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0010_heavy_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Moderate or heavy rain shower",
                },
              ],
              precipMM: "2.6",
              precipInches: "0.1",
              humidity: "73",
              visibility: "7",
              visibilityMiles: "4",
              pressure: "1006",
              pressureInches: "30",
              cloudcover: "79",
              HeatIndexC: "11",
              HeatIndexF: "52",
              DewPointC: "7",
              DewPointF: "44",
              WindChillC: "7",
              WindChillF: "45",
              WindGustMiles: "45",
              WindGustKmph: "73",
              FeelsLikeC: "7",
              FeelsLikeF: "45",
              sigHeight_m: "1.9",
              swellHeight_m: "3.9",
              swellHeight_ft: "12.8",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.8",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "2100",
              tempC: "10",
              tempF: "51",
              windspeedMiles: "31",
              windspeedKmph: "49",
              winddirDegree: "292",
              winddir16Point: "WNW",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "0.5",
              precipInches: "0.0",
              humidity: "67",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1007",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "10",
              HeatIndexF: "51",
              DewPointC: "5",
              DewPointF: "40",
              WindChillC: "6",
              WindChillF: "43",
              WindGustMiles: "38",
              WindGustKmph: "62",
              FeelsLikeC: "6",
              FeelsLikeF: "43",
              sigHeight_m: "1.5",
              swellHeight_m: "3.7",
              swellHeight_ft: "12.1",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.2",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
          ],
        },
        {
          date: "2021-01-25",
          astronomy: [
            {
              sunrise: "08:33 AM",
              sunset: "06:05 PM",
              moonrise: "02:49 PM",
              moonset: "05:58 AM",
              moon_phase: "Full Moon",
              moon_illumination: "83",
            },
          ],
          maxtempC: "10",
          maxtempF: "51",
          mintempC: "9",
          mintempF: "49",
          hourly: [
            {
              time: "0",
              tempC: "9",
              tempF: "49",
              windspeedMiles: "31",
              windspeedKmph: "49",
              winddirDegree: "299",
              winddir16Point: "WNW",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "0.6",
              precipInches: "0.0",
              humidity: "63",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1010",
              pressureInches: "30",
              cloudcover: "91",
              HeatIndexC: "9",
              HeatIndexF: "49",
              DewPointC: "3",
              DewPointF: "37",
              WindChillC: "6",
              WindChillF: "42",
              WindGustMiles: "42",
              WindGustKmph: "67",
              FeelsLikeC: "6",
              FeelsLikeF: "42",
              sigHeight_m: "1.7",
              swellHeight_m: "3.5",
              swellHeight_ft: "11.5",
              swellDir: "230",
              swellDir16Point: "SW",
              swellPeriod_secs: "18.0",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "300",
              tempC: "9",
              tempF: "49",
              windspeedMiles: "26",
              windspeedKmph: "41",
              winddirDegree: "307",
              winddir16Point: "NW",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "59",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1011",
              pressureInches: "30",
              cloudcover: "82",
              HeatIndexC: "9",
              HeatIndexF: "49",
              DewPointC: "2",
              DewPointF: "35",
              WindChillC: "6",
              WindChillF: "43",
              WindGustMiles: "37",
              WindGustKmph: "59",
              FeelsLikeC: "6",
              FeelsLikeF: "43",
              sigHeight_m: "1.7",
              swellHeight_m: "3.3",
              swellHeight_ft: "10.8",
              swellDir: "230",
              swellDir16Point: "SW",
              swellPeriod_secs: "17.6",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "600",
              tempC: "10",
              tempF: "49",
              windspeedMiles: "18",
              windspeedKmph: "29",
              winddirDegree: "341",
              winddir16Point: "NNW",
              weatherCode: "122",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Overcast",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "57",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1012",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "10",
              HeatIndexF: "49",
              DewPointC: "2",
              DewPointF: "35",
              WindChillC: "7",
              WindChillF: "44",
              WindGustMiles: "27",
              WindGustKmph: "43",
              FeelsLikeC: "7",
              FeelsLikeF: "44",
              sigHeight_m: "0.7",
              swellHeight_m: "3.1",
              swellHeight_ft: "10.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "9.9",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "900",
              tempC: "10",
              tempF: "49",
              windspeedMiles: "16",
              windspeedKmph: "26",
              winddirDegree: "1",
              winddir16Point: "N",
              weatherCode: "122",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Overcast",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "57",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1012",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "10",
              HeatIndexF: "49",
              DewPointC: "1",
              DewPointF: "35",
              WindChillC: "7",
              WindChillF: "45",
              WindGustMiles: "25",
              WindGustKmph: "41",
              FeelsLikeC: "7",
              FeelsLikeF: "45",
              sigHeight_m: "0.7",
              swellHeight_m: "2.9",
              swellHeight_ft: "9.5",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "9.9",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1200",
              tempC: "10",
              tempF: "49",
              windspeedMiles: "11",
              windspeedKmph: "18",
              winddirDegree: "10",
              winddir16Point: "N",
              weatherCode: "122",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Overcast",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "63",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1013",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "10",
              HeatIndexF: "49",
              DewPointC: "3",
              DewPointF: "38",
              WindChillC: "7",
              WindChillF: "45",
              WindGustMiles: "17",
              WindGustKmph: "27",
              FeelsLikeC: "7",
              FeelsLikeF: "45",
              sigHeight_m: "0.4",
              swellHeight_m: "2.7",
              swellHeight_ft: "8.9",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "10.3",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1500",
              tempC: "10",
              tempF: "50",
              windspeedMiles: "9",
              windspeedKmph: "14",
              winddirDegree: "345",
              winddir16Point: "NNW",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "63",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1012",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "10",
              HeatIndexF: "50",
              DewPointC: "3",
              DewPointF: "38",
              WindChillC: "8",
              WindChillF: "46",
              WindGustMiles: "15",
              WindGustKmph: "25",
              FeelsLikeC: "8",
              FeelsLikeF: "46",
              sigHeight_m: "0.3",
              swellHeight_m: "2.5",
              swellHeight_ft: "8.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "10.6",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1800",
              tempC: "10",
              tempF: "50",
              windspeedMiles: "7",
              windspeedKmph: "12",
              winddirDegree: "348",
              winddir16Point: "NNW",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "0.2",
              precipInches: "0.0",
              humidity: "65",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1013",
              pressureInches: "30",
              cloudcover: "97",
              HeatIndexC: "10",
              HeatIndexF: "50",
              DewPointC: "4",
              DewPointF: "39",
              WindChillC: "8",
              WindChillF: "46",
              WindGustMiles: "17",
              WindGustKmph: "28",
              FeelsLikeC: "8",
              FeelsLikeF: "46",
              sigHeight_m: "0.2",
              swellHeight_m: "2.4",
              swellHeight_ft: "7.9",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "14.5",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "2100",
              tempC: "10",
              tempF: "51",
              windspeedMiles: "4",
              windspeedKmph: "6",
              winddirDegree: "346",
              winddir16Point: "NNW",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "65",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1015",
              pressureInches: "30",
              cloudcover: "80",
              HeatIndexC: "10",
              HeatIndexF: "51",
              DewPointC: "4",
              DewPointF: "39",
              WindChillC: "8",
              WindChillF: "47",
              WindGustMiles: "14",
              WindGustKmph: "22",
              FeelsLikeC: "8",
              FeelsLikeF: "47",
              sigHeight_m: "0.1",
              swellHeight_m: "2.2",
              swellHeight_ft: "7.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "14.3",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
          ],
        },
        {
          date: "2021-01-26",
          astronomy: [
            {
              sunrise: "08:32 AM",
              sunset: "06:06 PM",
              moonrise: "03:39 PM",
              moonset: "06:58 AM",
              moon_phase: "Full Moon",
              moon_illumination: "90",
            },
          ],
          maxtempC: "12",
          maxtempF: "54",
          mintempC: "9",
          mintempF: "48",
          hourly: [
            {
              time: "0",
              tempC: "10",
              tempF: "51",
              windspeedMiles: "2",
              windspeedKmph: "4",
              winddirDegree: "123",
              winddir16Point: "ESE",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "0.2",
              precipInches: "0.0",
              humidity: "67",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1016",
              pressureInches: "30",
              cloudcover: "70",
              HeatIndexC: "10",
              HeatIndexF: "51",
              DewPointC: "5",
              DewPointF: "40",
              WindChillC: "8",
              WindChillF: "47",
              WindGustMiles: "13",
              WindGustKmph: "21",
              FeelsLikeC: "8",
              FeelsLikeF: "47",
              sigHeight_m: "0.1",
              swellHeight_m: "2.1",
              swellHeight_ft: "6.9",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "14.2",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "300",
              tempC: "10",
              tempF: "51",
              windspeedMiles: "9",
              windspeedKmph: "14",
              winddirDegree: "154",
              winddir16Point: "SSE",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "64",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1017",
              pressureInches: "31",
              cloudcover: "79",
              HeatIndexC: "10",
              HeatIndexF: "51",
              DewPointC: "4",
              DewPointF: "39",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "22",
              WindGustKmph: "35",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "0.3",
              swellHeight_m: "1.9",
              swellHeight_ft: "6.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "14.0",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "600",
              tempC: "10",
              tempF: "51",
              windspeedMiles: "14",
              windspeedKmph: "22",
              winddirDegree: "142",
              winddir16Point: "SE",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "60",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1017",
              pressureInches: "31",
              cloudcover: "77",
              HeatIndexC: "10",
              HeatIndexF: "51",
              DewPointC: "3",
              DewPointF: "37",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "23",
              WindGustKmph: "37",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "0.5",
              swellHeight_m: "1.8",
              swellHeight_ft: "5.9",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "13.2",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "900",
              tempC: "10",
              tempF: "50",
              windspeedMiles: "18",
              windspeedKmph: "28",
              winddirDegree: "148",
              winddir16Point: "SSE",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "73",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1018",
              pressureInches: "31",
              cloudcover: "68",
              HeatIndexC: "10",
              HeatIndexF: "50",
              DewPointC: "5",
              DewPointF: "42",
              WindChillC: "7",
              WindChillF: "45",
              WindGustMiles: "27",
              WindGustKmph: "43",
              FeelsLikeC: "7",
              FeelsLikeF: "45",
              sigHeight_m: "0.7",
              swellHeight_m: "1.7",
              swellHeight_ft: "5.6",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "13.1",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1200",
              tempC: "9",
              tempF: "48",
              windspeedMiles: "18",
              windspeedKmph: "29",
              winddirDegree: "153",
              winddir16Point: "SSE",
              weatherCode: "296",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0017_cloudy_with_light_rain.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain",
                },
              ],
              precipMM: "1.2",
              precipInches: "0.0",
              humidity: "89",
              visibility: "9",
              visibilityMiles: "5",
              pressure: "1018",
              pressureInches: "31",
              cloudcover: "100",
              HeatIndexC: "9",
              HeatIndexF: "48",
              DewPointC: "7",
              DewPointF: "45",
              WindChillC: "6",
              WindChillF: "43",
              WindGustMiles: "20",
              WindGustKmph: "32",
              FeelsLikeC: "6",
              FeelsLikeF: "43",
              sigHeight_m: "0.7",
              swellHeight_m: "1.6",
              swellHeight_ft: "5.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "13.0",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1500",
              tempC: "10",
              tempF: "50",
              windspeedMiles: "16",
              windspeedKmph: "26",
              winddirDegree: "154",
              winddir16Point: "SSE",
              weatherCode: "266",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0017_cloudy_with_light_rain.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light drizzle",
                },
              ],
              precipMM: "0.3",
              precipInches: "0.0",
              humidity: "91",
              visibility: "2",
              visibilityMiles: "1",
              pressure: "1017",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "10",
              HeatIndexF: "50",
              DewPointC: "8",
              DewPointF: "47",
              WindChillC: "6",
              WindChillF: "44",
              WindGustMiles: "24",
              WindGustKmph: "39",
              FeelsLikeC: "6",
              FeelsLikeF: "44",
              sigHeight_m: "0.6",
              swellHeight_m: "1.5",
              swellHeight_ft: "4.9",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "12.8",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1800",
              tempC: "12",
              tempF: "54",
              windspeedMiles: "20",
              windspeedKmph: "32",
              winddirDegree: "194",
              winddir16Point: "SSW",
              weatherCode: "266",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0017_cloudy_with_light_rain.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light drizzle",
                },
              ],
              precipMM: "0.6",
              precipInches: "0.0",
              humidity: "96",
              visibility: "2",
              visibilityMiles: "1",
              pressure: "1017",
              pressureInches: "31",
              cloudcover: "100",
              HeatIndexC: "12",
              HeatIndexF: "54",
              DewPointC: "12",
              DewPointF: "53",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "23",
              WindGustKmph: "37",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "0.9",
              swellHeight_m: "1.4",
              swellHeight_ft: "4.6",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "12.2",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "2100",
              tempC: "12",
              tempF: "54",
              windspeedMiles: "21",
              windspeedKmph: "33",
              winddirDegree: "270",
              winddir16Point: "W",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "0.2",
              precipInches: "0.0",
              humidity: "94",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1019",
              pressureInches: "31",
              cloudcover: "86",
              HeatIndexC: "12",
              HeatIndexF: "54",
              DewPointC: "12",
              DewPointF: "53",
              WindChillC: "10",
              WindChillF: "49",
              WindGustMiles: "29",
              WindGustKmph: "47",
              FeelsLikeC: "10",
              FeelsLikeF: "49",
              sigHeight_m: "0.9",
              swellHeight_m: "1.4",
              swellHeight_ft: "4.6",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "12.0",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
          ],
        },
        {
          date: "2021-01-27",
          astronomy: [
            {
              sunrise: "08:31 AM",
              sunset: "06:08 PM",
              moonrise: "04:37 PM",
              moonset: "07:51 AM",
              moon_phase: "Full Moon",
              moon_illumination: "97",
            },
          ],
          maxtempC: "14",
          maxtempF: "57",
          mintempC: "12",
          mintempF: "53",
          hourly: [
            {
              time: "0",
              tempC: "12",
              tempF: "54",
              windspeedMiles: "24",
              windspeedKmph: "39",
              winddirDegree: "287",
              winddir16Point: "WNW",
              weatherCode: "266",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light drizzle",
                },
              ],
              precipMM: "0.2",
              precipInches: "0.0",
              humidity: "91",
              visibility: "2",
              visibilityMiles: "1",
              pressure: "1021",
              pressureInches: "31",
              cloudcover: "99",
              HeatIndexC: "12",
              HeatIndexF: "54",
              DewPointC: "11",
              DewPointF: "51",
              WindChillC: "10",
              WindChillF: "49",
              WindGustMiles: "26",
              WindGustKmph: "42",
              FeelsLikeC: "10",
              FeelsLikeF: "49",
              sigHeight_m: "1.1",
              swellHeight_m: "1.5",
              swellHeight_ft: "4.9",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.4",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "300",
              tempC: "12",
              tempF: "54",
              windspeedMiles: "16",
              windspeedKmph: "26",
              winddirDegree: "290",
              winddir16Point: "WNW",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "87",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1021",
              pressureInches: "31",
              cloudcover: "87",
              HeatIndexC: "12",
              HeatIndexF: "54",
              DewPointC: "10",
              DewPointF: "50",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "21",
              WindGustKmph: "33",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "0.7",
              swellHeight_m: "1.6",
              swellHeight_ft: "5.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "11.5",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "600",
              tempC: "12",
              tempF: "53",
              windspeedMiles: "12",
              windspeedKmph: "20",
              winddirDegree: "262",
              winddir16Point: "W",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "91",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1021",
              pressureInches: "31",
              cloudcover: "66",
              HeatIndexC: "12",
              HeatIndexF: "53",
              DewPointC: "10",
              DewPointF: "51",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "16",
              WindGustKmph: "26",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "0.5",
              swellHeight_m: "1.6",
              swellHeight_ft: "5.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "6.3",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "900",
              tempC: "12",
              tempF: "53",
              windspeedMiles: "14",
              windspeedKmph: "23",
              winddirDegree: "229",
              winddir16Point: "SW",
              weatherCode: "122",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Overcast",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "91",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1021",
              pressureInches: "31",
              cloudcover: "100",
              HeatIndexC: "12",
              HeatIndexF: "53",
              DewPointC: "11",
              DewPointF: "51",
              WindChillC: "10",
              WindChillF: "49",
              WindGustMiles: "21",
              WindGustKmph: "33",
              FeelsLikeC: "10",
              FeelsLikeF: "49",
              sigHeight_m: "0.6",
              swellHeight_m: "1.6",
              swellHeight_ft: "5.2",
              swellDir: "230",
              swellDir16Point: "SW",
              swellPeriod_secs: "6.9",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1200",
              tempC: "12",
              tempF: "54",
              windspeedMiles: "20",
              windspeedKmph: "32",
              winddirDegree: "235",
              winddir16Point: "SW",
              weatherCode: "302",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0018_cloudy_with_heavy_rain.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Moderate rain",
                },
              ],
              precipMM: "4.9",
              precipInches: "0.2",
              humidity: "97",
              visibility: "7",
              visibilityMiles: "4",
              pressure: "1021",
              pressureInches: "31",
              cloudcover: "100",
              HeatIndexC: "12",
              HeatIndexF: "54",
              DewPointC: "12",
              DewPointF: "53",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "21",
              WindGustKmph: "34",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "1.6",
              swellHeight_m: "1.6",
              swellHeight_ft: "5.2",
              swellDir: "240",
              swellDir16Point: "WSW",
              swellPeriod_secs: "11.5",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1500",
              tempC: "13",
              tempF: "55",
              windspeedMiles: "15",
              windspeedKmph: "24",
              winddirDegree: "229",
              winddir16Point: "SW",
              weatherCode: "263",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy light drizzle",
                },
              ],
              precipMM: "0.3",
              precipInches: "0.0",
              humidity: "93",
              visibility: "5",
              visibilityMiles: "3",
              pressure: "1019",
              pressureInches: "31",
              cloudcover: "66",
              HeatIndexC: "13",
              HeatIndexF: "55",
              DewPointC: "12",
              DewPointF: "54",
              WindChillC: "11",
              WindChillF: "52",
              WindGustMiles: "26",
              WindGustKmph: "42",
              FeelsLikeC: "11",
              FeelsLikeF: "52",
              sigHeight_m: "0.6",
              swellHeight_m: "1.6",
              swellHeight_ft: "5.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "11.1",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1800",
              tempC: "14",
              tempF: "56",
              windspeedMiles: "19",
              windspeedKmph: "30",
              winddirDegree: "200",
              winddir16Point: "SSW",
              weatherCode: "263",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy light drizzle",
                },
              ],
              precipMM: "0.4",
              precipInches: "0.0",
              humidity: "88",
              visibility: "5",
              visibilityMiles: "3",
              pressure: "1017",
              pressureInches: "31",
              cloudcover: "65",
              HeatIndexC: "14",
              HeatIndexF: "56",
              DewPointC: "12",
              DewPointF: "53",
              WindChillC: "12",
              WindChillF: "53",
              WindGustMiles: "28",
              WindGustKmph: "44",
              FeelsLikeC: "12",
              FeelsLikeF: "53",
              sigHeight_m: "0.8",
              swellHeight_m: "1.7",
              swellHeight_ft: "5.6",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "10.9",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "2100",
              tempC: "14",
              tempF: "57",
              windspeedMiles: "22",
              windspeedKmph: "35",
              winddirDegree: "191",
              winddir16Point: "SSW",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "0.2",
              precipInches: "0.0",
              humidity: "87",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1017",
              pressureInches: "31",
              cloudcover: "78",
              HeatIndexC: "14",
              HeatIndexF: "57",
              DewPointC: "12",
              DewPointF: "53",
              WindChillC: "11",
              WindChillF: "52",
              WindGustMiles: "40",
              WindGustKmph: "65",
              FeelsLikeC: "11",
              FeelsLikeF: "52",
              sigHeight_m: "0.9",
              swellHeight_m: "1.9",
              swellHeight_ft: "6.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "10.8",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
          ],
        },
        {
          date: "2021-01-28",
          astronomy: [
            {
              sunrise: "08:30 AM",
              sunset: "06:09 PM",
              moonrise: "05:44 PM",
              moonset: "08:37 AM",
              moon_phase: "Waning Gibbous",
              moon_illumination: "97",
            },
          ],
          maxtempC: "14",
          maxtempF: "58",
          mintempC: "13",
          mintempF: "55",
          hourly: [
            {
              time: "0",
              tempC: "13",
              tempF: "56",
              windspeedMiles: "23",
              windspeedKmph: "37",
              winddirDegree: "238",
              winddir16Point: "WSW",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "1.0",
              precipInches: "0.0",
              humidity: "88",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1018",
              pressureInches: "31",
              cloudcover: "87",
              HeatIndexC: "13",
              HeatIndexF: "56",
              DewPointC: "11",
              DewPointF: "53",
              WindChillC: "10",
              WindChillF: "51",
              WindGustMiles: "45",
              WindGustKmph: "72",
              FeelsLikeC: "10",
              FeelsLikeF: "51",
              sigHeight_m: "1.0",
              swellHeight_m: "2.2",
              swellHeight_ft: "7.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "17.5",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "300",
              tempC: "13",
              tempF: "55",
              windspeedMiles: "24",
              windspeedKmph: "39",
              winddirDegree: "254",
              winddir16Point: "WSW",
              weatherCode: "116",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Partly cloudy",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "85",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1019",
              pressureInches: "31",
              cloudcover: "7",
              HeatIndexC: "13",
              HeatIndexF: "55",
              DewPointC: "10",
              DewPointF: "50",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "28",
              WindGustKmph: "45",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "1.1",
              swellHeight_m: "2.3",
              swellHeight_ft: "7.5",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "16.3",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "600",
              tempC: "13",
              tempF: "55",
              windspeedMiles: "27",
              windspeedKmph: "44",
              winddirDegree: "266",
              winddir16Point: "W",
              weatherCode: "119",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Cloudy",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "84",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1018",
              pressureInches: "31",
              cloudcover: "79",
              HeatIndexC: "13",
              HeatIndexF: "55",
              DewPointC: "10",
              DewPointF: "50",
              WindChillC: "11",
              WindChillF: "51",
              WindGustMiles: "40",
              WindGustKmph: "65",
              FeelsLikeC: "11",
              FeelsLikeF: "51",
              sigHeight_m: "1.3",
              swellHeight_m: "3.1",
              swellHeight_ft: "10.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "0.7",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "900",
              tempC: "13",
              tempF: "55",
              windspeedMiles: "27",
              windspeedKmph: "43",
              winddirDegree: "256",
              winddir16Point: "WSW",
              weatherCode: "122",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Overcast",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "89",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1018",
              pressureInches: "31",
              cloudcover: "100",
              HeatIndexC: "13",
              HeatIndexF: "55",
              DewPointC: "11",
              DewPointF: "51",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "32",
              WindGustKmph: "51",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "1.2",
              swellHeight_m: "3.6",
              swellHeight_ft: "11.8",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "15.5",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1200",
              tempC: "13",
              tempF: "55",
              windspeedMiles: "26",
              windspeedKmph: "41",
              winddirDegree: "246",
              winddir16Point: "WSW",
              weatherCode: "119",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0003_white_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Cloudy",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "89",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1017",
              pressureInches: "30",
              cloudcover: "68",
              HeatIndexC: "13",
              HeatIndexF: "55",
              DewPointC: "11",
              DewPointF: "52",
              WindChillC: "10",
              WindChillF: "51",
              WindGustMiles: "34",
              WindGustKmph: "55",
              FeelsLikeC: "10",
              FeelsLikeF: "51",
              sigHeight_m: "1.2",
              swellHeight_m: "3.8",
              swellHeight_ft: "12.5",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "13.8",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1500",
              tempC: "14",
              tempF: "56",
              windspeedMiles: "23",
              windspeedKmph: "37",
              winddirDegree: "252",
              winddir16Point: "WSW",
              weatherCode: "266",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0017_cloudy_with_light_rain.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light drizzle",
                },
              ],
              precipMM: "0.8",
              precipInches: "0.0",
              humidity: "82",
              visibility: "2",
              visibilityMiles: "1",
              pressure: "1014",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "14",
              HeatIndexF: "56",
              DewPointC: "11",
              DewPointF: "51",
              WindChillC: "12",
              WindChillF: "53",
              WindGustMiles: "34",
              WindGustKmph: "54",
              FeelsLikeC: "12",
              FeelsLikeF: "53",
              sigHeight_m: "1.0",
              swellHeight_m: "4.0",
              swellHeight_ft: "13.1",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "14.1",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1800",
              tempC: "14",
              tempF: "58",
              windspeedMiles: "17",
              windspeedKmph: "27",
              winddirDegree: "246",
              winddir16Point: "WSW",
              weatherCode: "263",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0009_light_rain_showers.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy light drizzle",
                },
              ],
              precipMM: "0.8",
              precipInches: "0.0",
              humidity: "77",
              visibility: "5",
              visibilityMiles: "3",
              pressure: "1012",
              pressureInches: "30",
              cloudcover: "62",
              HeatIndexC: "14",
              HeatIndexF: "58",
              DewPointC: "10",
              DewPointF: "51",
              WindChillC: "12",
              WindChillF: "54",
              WindGustMiles: "40",
              WindGustKmph: "65",
              FeelsLikeC: "12",
              FeelsLikeF: "54",
              sigHeight_m: "0.7",
              swellHeight_m: "4.1",
              swellHeight_ft: "13.5",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "14.3",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "2100",
              tempC: "14",
              tempF: "57",
              windspeedMiles: "18",
              windspeedKmph: "29",
              winddirDegree: "229",
              winddir16Point: "SW",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.1",
              precipInches: "0.0",
              humidity: "81",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1010",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "14",
              HeatIndexF: "57",
              DewPointC: "11",
              DewPointF: "52",
              WindChillC: "11",
              WindChillF: "52",
              WindGustMiles: "36",
              WindGustKmph: "58",
              FeelsLikeC: "11",
              FeelsLikeF: "52",
              sigHeight_m: "0.8",
              swellHeight_m: "4.0",
              swellHeight_ft: "13.1",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "14.3",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
          ],
        },
        {
          date: "2021-01-29",
          astronomy: [
            {
              sunrise: "08:29 AM",
              sunset: "06:10 PM",
              moonrise: "06:56 PM",
              moonset: "09:17 AM",
              moon_phase: "Waning Gibbous",
              moon_illumination: "90",
            },
          ],
          maxtempC: "14",
          maxtempF: "57",
          mintempC: "12",
          mintempF: "53",
          hourly: [
            {
              time: "0",
              tempC: "14",
              tempF: "57",
              windspeedMiles: "24",
              windspeedKmph: "39",
              winddirDegree: "223",
              winddir16Point: "SW",
              weatherCode: "296",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0033_cloudy_with_light_rain_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain",
                },
              ],
              precipMM: "1.8",
              precipInches: "0.1",
              humidity: "88",
              visibility: "9",
              visibilityMiles: "5",
              pressure: "1011",
              pressureInches: "30",
              cloudcover: "100",
              HeatIndexC: "14",
              HeatIndexF: "57",
              DewPointC: "12",
              DewPointF: "53",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "42",
              WindGustKmph: "68",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "1.1",
              swellHeight_m: "3.7",
              swellHeight_ft: "12.1",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "14.1",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "300",
              tempC: "13",
              tempF: "55",
              windspeedMiles: "21",
              windspeedKmph: "35",
              winddirDegree: "240",
              winddir16Point: "WSW",
              weatherCode: "353",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light rain shower",
                },
              ],
              precipMM: "0.6",
              precipInches: "0.0",
              humidity: "84",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1013",
              pressureInches: "30",
              cloudcover: "92",
              HeatIndexC: "13",
              HeatIndexF: "55",
              DewPointC: "10",
              DewPointF: "51",
              WindChillC: "10",
              WindChillF: "49",
              WindGustMiles: "39",
              WindGustKmph: "63",
              FeelsLikeC: "10",
              FeelsLikeF: "49",
              sigHeight_m: "0.9",
              swellHeight_m: "3.4",
              swellHeight_ft: "11.2",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "13.6",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "600",
              tempC: "12",
              tempF: "54",
              windspeedMiles: "21",
              windspeedKmph: "33",
              winddirDegree: "249",
              winddir16Point: "WSW",
              weatherCode: "176",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0025_light_rain_showers_night.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Patchy rain possible",
                },
              ],
              precipMM: "0.5",
              precipInches: "0.0",
              humidity: "81",
              visibility: "9",
              visibilityMiles: "5",
              pressure: "1015",
              pressureInches: "30",
              cloudcover: "72",
              HeatIndexC: "12",
              HeatIndexF: "54",
              DewPointC: "9",
              DewPointF: "48",
              WindChillC: "9",
              WindChillF: "48",
              WindGustMiles: "35",
              WindGustKmph: "57",
              FeelsLikeC: "9",
              FeelsLikeF: "48",
              sigHeight_m: "0.9",
              swellHeight_m: "3.3",
              swellHeight_ft: "10.8",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "13.2",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "900",
              tempC: "12",
              tempF: "53",
              windspeedMiles: "27",
              windspeedKmph: "43",
              winddirDegree: "238",
              winddir16Point: "WSW",
              weatherCode: "116",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Partly cloudy",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "83",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1018",
              pressureInches: "31",
              cloudcover: "13",
              HeatIndexC: "12",
              HeatIndexF: "53",
              DewPointC: "9",
              DewPointF: "48",
              WindChillC: "9",
              WindChillF: "49",
              WindGustMiles: "40",
              WindGustKmph: "64",
              FeelsLikeC: "9",
              FeelsLikeF: "49",
              sigHeight_m: "1.2",
              swellHeight_m: "3.5",
              swellHeight_ft: "11.5",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "12.9",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1200",
              tempC: "12",
              tempF: "53",
              windspeedMiles: "23",
              windspeedKmph: "37",
              winddirDegree: "240",
              winddir16Point: "WSW",
              weatherCode: "116",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0002_sunny_intervals.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Partly cloudy",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "84",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1020",
              pressureInches: "31",
              cloudcover: "22",
              HeatIndexC: "12",
              HeatIndexF: "53",
              DewPointC: "9",
              DewPointF: "49",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "30",
              WindGustKmph: "48",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "1.0",
              swellHeight_m: "3.7",
              swellHeight_ft: "12.1",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "12.7",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1500",
              tempC: "12",
              tempF: "54",
              windspeedMiles: "19",
              windspeedKmph: "31",
              winddirDegree: "234",
              winddir16Point: "SW",
              weatherCode: "122",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Overcast",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "87",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1020",
              pressureInches: "31",
              cloudcover: "100",
              HeatIndexC: "12",
              HeatIndexF: "54",
              DewPointC: "10",
              DewPointF: "50",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "30",
              WindGustKmph: "49",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "0.8",
              swellHeight_m: "3.7",
              swellHeight_ft: "12.1",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "12.6",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "1800",
              tempC: "12",
              tempF: "54",
              windspeedMiles: "13",
              windspeedKmph: "22",
              winddirDegree: "224",
              winddir16Point: "SW",
              weatherCode: "266",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0017_cloudy_with_light_rain.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Light drizzle",
                },
              ],
              precipMM: "0.3",
              precipInches: "0.0",
              humidity: "95",
              visibility: "2",
              visibilityMiles: "1",
              pressure: "1020",
              pressureInches: "31",
              cloudcover: "98",
              HeatIndexC: "12",
              HeatIndexF: "54",
              DewPointC: "12",
              DewPointF: "53",
              WindChillC: "10",
              WindChillF: "50",
              WindGustMiles: "26",
              WindGustKmph: "42",
              FeelsLikeC: "10",
              FeelsLikeF: "50",
              sigHeight_m: "0.5",
              swellHeight_m: "3.6",
              swellHeight_ft: "11.8",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "12.9",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
            {
              time: "2100",
              tempC: "13",
              tempF: "55",
              windspeedMiles: "9",
              windspeedKmph: "15",
              winddirDegree: "141",
              winddir16Point: "SE",
              weatherCode: "116",
              weatherIconUrl: [
                {
                  value:
                    "http://cdn.worldweatheronline.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
                },
              ],
              weatherDesc: [
                {
                  value: "Partly cloudy",
                },
              ],
              precipMM: "0.0",
              precipInches: "0.0",
              humidity: "95",
              visibility: "10",
              visibilityMiles: "6",
              pressure: "1020",
              pressureInches: "31",
              cloudcover: "40",
              HeatIndexC: "13",
              HeatIndexF: "55",
              DewPointC: "12",
              DewPointF: "54",
              WindChillC: "11",
              WindChillF: "52",
              WindGustMiles: "21",
              WindGustKmph: "34",
              FeelsLikeC: "11",
              FeelsLikeF: "52",
              sigHeight_m: "0.3",
              swellHeight_m: "3.5",
              swellHeight_ft: "11.5",
              swellDir: "330",
              swellDir16Point: "NNW",
              swellPeriod_secs: "13.3",
              waterTemp_C: "11",
              waterTemp_F: "52",
            },
          ],
        },
      ],
    },
  };
  // return data;
};

/**
 * Get the historical track of a vessel
 * @params {String} mssi
 * @return {Object}
 */

export const getHistoricalTrackOfAVessel = async (mmsi) => {
  const result = await axios.get(
    `https://services.marinetraffic.com/api/exportvesseltrack/${constants.MARINE_TRAFFIC_API_KEY}/v:2/period:daily/days:3/mmsi:${mmsi}`
  );
  console.log(result);
  return result;
};

/**
 * Get the predictions
 * @params {Object} data
 * @return {Object}
 */

export const getPredictions = async (data) => {
  const result = await axios.post(
    `https://aispredictor.herokuapp.com/predict`,
    data
  );
  return result;
};
